export const blogs = [
  {
    id: 1,
    title: "Getting Started with JavaScript",
    author: "John Doe",
    category: "Programming",
    publishedAt: "2026-07-01",
    tags: ["JavaScript", "Beginner", "Web Development"],
    summary:
      "Learn the fundamentals of JavaScript and start building interactive websites.",
    image: "https://example.com/images/javascript.jpg",
    readTime: "5 min",
  },
  {
    id: 2,
    title: "10 Tips for Better UI Design",
    author: "Sarah Smith",
    category: "Design",
    publishedAt: "2026-07-03",
    tags: ["UI", "UX", "Design"],
    summary: "Discover practical tips to improve your user interface designs.",
    image: "https://example.com/images/ui-design.jpg",
    readTime: "7 min",
  },
  {
    id: 3,
    title: "Understanding React Hooks",
    author: "Michael Brown",
    category: "React",
    publishedAt: "2026-07-05",
    tags: ["React", "Hooks", "Frontend"],
    summary: "A beginner-friendly guide to using React Hooks effectively.",
    image: "https://example.com/images/react-hooks.jpg",
    readTime: "8 min",
  },
  {
    id: 4,
    title: "Node.js Best Practices",
    author: "Emily Davis",
    category: "Backend",
    publishedAt: "2026-07-08",
    tags: ["Node.js", "API", "Backend"],
    summary:
      "Learn the best practices for building scalable Node.js applications.",
    image: "https://example.com/images/nodejs.jpg",
    readTime: "6 min",
  },
  {
    id: 5,
    title: "Introduction to TypeScript",
    author: "David Wilson",
    category: "Programming",
    publishedAt: "2026-07-10",
    tags: ["TypeScript", "JavaScript"],
    summary:
      "Explore why TypeScript is becoming the preferred choice for large applications.",
    image: "https://example.com/images/typescript.jpg",
    readTime: "9 min",
  },
];
