// // console.log("hello world");
// // console.warn("hello world");
// // console.error("hello world");
// // console.log(__dirname);
// // console.log(__filename);
// // console.time();
// // for (var i = 0; i < 5; i++) {
// //   console.log(i);
// // }
// const os = require("os");
// // console.timeEnd();
// // console.log(Os.arch());
// // console.log(process.cwd());
// // console.log(process.version);
// // console.log(process.platform);
// console.log(os.arch());
// // console.log(os.cpus());
// console.log(os.freemem());
// console.log(os.endianness());
// console.log(os.homedir());
// console.log(os.hostname());
// console.log(os.loadavg());
// console.log(os.networkInterfaces());
// console.log(os.release());
// console.log(os.platform());
// console.log(os.tmpdir());
// console.log(os.totalmem());
// console.log(os.type());
// console.log(os.uptime());
// console.log(os.userInfo());
